[tool.poetry]
name = "kowalski-core"
version = "0.1.0"
description = ""
authors = ["Matteo Ferrini <mimmi.ferrini@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
kowalski-core = "kowalski_core.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.12.5"
trafilatura = "^1.12.2"
youtube-transcript-api = "^0.6.2"
pyyaml = "^6.0.2"
groq = "^0.11.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"