[project]
name = "kowalski-core"
version = "0.2.0"
description = "kowalski-core is a simple think-it-later app for your CLI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer>=0.15.1",
    "trafilatura>=2.0.0",
    "youtube-transcript-api>=0.6.3",
    "chromadb>=0.6.0",
]

[project.scripts]
kv = "kowalski_core.main:app"
