Output assets/pictures/demo.gif

Set FontSize 20
Set Width 1200
Set Height 600

Type "ko add"
Sleep 1s
Enter
Sleep 1s

Down 6

Type "Welcome to Kowalski!"
Sleep 2s
Ctrl+O
Sleep 1s
Enter
Sleep 1s
Ctrl+X
Sleep 2s

Type "ko list"
Sleep 1s
Enter
Sleep 2s

Type "ko save https://www.youtube.com/watch?v=mBFf-aYoV6Q"
Sleep 1s
Enter
Sleep 2s

Type "ko show 201406-250109.md | mods 'Please summarize this in two sentences'""
Sleep 1s
Enter
Sleep 10s